@BookFlow.Api_HostAddress = http://localhost:5257
GET {{BookFlow.Api_HostAddress}}/api/reservations
Accept: application/json
###

GET {{BookFlow.Api_HostAddress}}/api/reservations/1
Accept: application/json

###

GET {{BookFlow.Api_HostAddress}}/api/reservations/999
Accept: application/json